### ISSUE TITLE
asking for unnecessary permissions

### ISSUE THREAD

**Issue by a1291762** [henrichg/PhoneProfiles#1]
Asks for root after every update but it doesn't need it (has separate permission to set/clear do not disturb).

Asks for storage to write sound files that are not even used.

**Comment by henrichg** [comment]
1. After app. update, application is restarted. Therefore ask for root is reuired in start of app.
2. PPP installing phoneprofiles_silent.ogg to folders: Alarms, Notifications, Ringtones, for using it by user. This tone can be used if device has merged ringing and notification volumes and in profile is configured notification volume=0.

**Comment by a1291762** [comment]
On 12 May 2017 2:02:24 AM AEST, Henrich Gron <notifications@github.com> wrote:
>1. After app. update, application is restarted. Therefore ask for root
>is reuired in start of app.
>2. PPP installing phoneprofiles_silent.ogg to folders: Alarms,
>Notifications, Ringtones, for using it by user. This tone can be used
>if device has merged ringing and notification volumes and in profile is
>configured notification volume=0.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/henrichg/PhoneProfiles/issues/1#issuecomment-300836532

I understand why it re-asks (that's a security feature of the su app). I don't understand why it asks for root when it doesn't need it. I don't use any settings that require root. I do set/clear the do not disturb state but gave the app permission to do that (via settings) so it works without root.

I have Android 6, so my volumes are merged but I do not set ringtone or notification volumes to a zero value. I do set the ringer to vibrate only and do not disturb but this is a separate setting. So I do not need the files, yet it still tries to write them.

I switched from another profiles app that didn't handle do not disturb and PhoneProfiles works fine. I just don't like it when apps ask for permissions they don't need and write files all over my storage. I can deny these permissions to PhoneProfiles so in practice there's no issue. But the re-asking for root happens on every upgrade and PhoneProfiles even tried to get me to re-enable the storage permission so it could write files that were not needed.


Sent from my Android

**Comment by henrichg** [comment]
"Grant root" is added in application Settings -> Permissions. This opens "Grant root" dialog with checkbox "Never ask again". Answer "No" with "Never ask again" checked and grant will never be asked after PP upgrade. Answer "Yes" and this opens SuperSU or Magisk Manager. ;-)
This will be in next version.
