### ISSUE TITLE
Can't run apps automatically by profile after force stop task

### ISSUE THREAD

**Issue by Dre-OS** [henrichg/PhoneProfiles#4]
After PhoneProfiler force stops an app, it can't also run the app that profile supposed to run. Please fix it, its a very useful feature for tasking

**Comment by henrichg** [comment]
You means after device boot? Or by profile with parameter "Run application, shortcut, intent"?

PhoneProfiles and also PhoneProfilesPlus uses for "Force stop applications" profile parameter, simulation of clicks to system App info screen. How working force stopped application after click to "Force stop" button is not by PP/PPP, but by system.

But I'm tested "Force stop applicaton" and "Run application, shortcut, intent" with configured Chrome app. In two separated profiles. "Force stop application" profile force stop Chrome. In It's App info screen, after force stop app profile activation, was "Force stop" button disabled. 
Next was activated profile with "Run application, shortcut, intent" and Chrome was started. 
By me, all working good.

**Comment by henrichg** [comment]
Warning: both profile parameters are ignored (not used) for first start of PP/PPP, for example after device boot.

**Comment by Dre-OS** [comment]
What if both profile parameters are applied in a single profile? i tested it; "force stop" parameter is fine and activated when i enabled the profile, but after that, the app i've assigned in the "Run applications, shortcuts, and intents" parameter did not run.

**Comment by Dre-OS** [comment]
In addition, the device was not rebooted and its last boot was a long time ago when this occured

**Comment by henrichg** [comment]
Maybe in profile activation is bug. Maybe order of calls, maybe time between both patameters. I will looking on it.

**Comment by henrichg** [comment]
In profile: you want to force stop application and then run it again? In run application: you have configured also startup delay parameter?

**Comment by Dre-OS** [comment]
In profile: no sir, i would like to replace running background application.
In run application: I did in the range of 1-3 seconds (4 and beyond is too long so i ignored) but still did not run

**Comment by henrichg** [comment]
In profile you have configured to force stop one application and run another application? In one profile? Write me, which application you have configured to force stop and which to run?

**Comment by Dre-OS** [comment]
I wanted to force stop batteryguru then run Advance Download Manager (ADM)

**Comment by henrichg** [comment]
Fixed. In this beta 5.0.0.15b (3581): https://drive.google.com/file/d/0B5RwcWvhmm8RNjF3Vy1RRDltSkE/view?usp=drivesdk
Before installation do backup of PP data. Backup is in Editor menu.

**Comment by Dre-OS** [comment]
It's working fine now, thanks dev

**Comment by Dre-OS** [comment]
Quick question, is there a way to port the settings of PP to PPP?

**Comment by henrichg** [comment]
Export data from PP into PPP is currently not possible. Backup data are not
compatible.
But it's scheduled, analyzed, how to export it.
Because PP is not more maintained. Only bugs fixed. New functions are added
only into PPP.

Dňa št 28. 5. 2020, 1:30 Dre-OS <notifications@github.com> napísal(a):
