### ISSUE TITLE
Launching specific app services

### ISSUE THREAD

**Issue by Dre-OS** [henrichg/PhoneProfiles#5]
Is there a way to launch a background service in  PhoneProfiles/PhoneProfilesPus without launching an app activity that shows up onscreen?

**Comment by henrichg** [comment]
If it is possible in application for which you want to start service, use in
profile, start of Intent, in parameter "Run application, shortcut, intent".

**Comment by Dre-OS** [comment]
I'm also curious as to how i input the specific background service, please tell me sir

**Comment by henrichg** [comment]
I do not known. You must send me application package name, it's service name. And maybe it is not possible for this application. When service configuration in application manifest file is not set as exported or action is not configured for start of this service, then this is not possible.

**Comment by Dre-OS** [comment]
App is: com.velis.auto.brightness
Service name is: Auto_Brightness_Service

**Comment by henrichg** [comment]
Auto brightness? This application, by me, must working all the time.
Send me, please, Google Play link.

**Comment by Dre-OS** [comment]
https://play.google.com/store/apps/details?id=com.velis.auto.brightness its an alternative to the built in autobrightness that the user controls better

**Comment by henrichg** [comment]
This is very old application. Your device do not have this functionality in device? Also PP has this functionality (enable/disable auto-brightness).

**Comment by Dre-OS** [comment]
Didn't see that now i do, thank you friend, this autobrightness app is somehow hard to setup

**Comment by henrichg** [comment]
Automatization is not in PP but PPP (PhoneProfilesPlus). PP is only for
manual profile activation.

**Comment by Dre-OS** [comment]
Ok, now i will get rid of the velis autobrightness and use your app instead to conserve resources,  thank you dev

**Comment by Dre-OS** [comment]
Hmn, sir dev, it seems that i can't activate or deactivate the adaptive brightness on the activator in PP, only in editor

**Comment by henrichg** [comment]
You must enable profile to show it in Activator. Parameter "Show in Activator".

**Comment by Dre-OS** [comment]
Like the adaptive brightness function is not working on the activator, it only works when i'm editing the parameter in the editor

**Comment by henrichg** [comment]
Must be set two values:
1. Adaptive brightness on/off
2. Adaptive brightness level: Is changed only when it is possible, For most devices is not possible to change adaptive brightness level without root.

Question: Which value was not changed by profile activation?

**Comment by Dre-OS** [comment]
The adaptive brightness on/off, it just activates when I select the setting but not when i actually activate the profile

**Comment by henrichg** [comment]
Please install this beta. In it, is loged, what is called for set brightness.
https://drive.google.com/file/d/0B5RwcWvhmm8RNjF3Vy1RRDltSkE/view?usp=drivesdk

Before installation do backup of PP data. Backup is in Editor menu.

After profile activation, use in Editor menu "Support/E-mail debug log files to author".

Thank you.

**Comment by Dre-OS** [comment]
Log has been sent, sir

**Comment by Dre-OS** [comment]
Hmn, i have restarted and it seems to be working fine now
